// Generated by Tegaki. The full-font fallback is intentionally omitted;
// lesson character coverage is enforced by tests/lesson-timeline.test.ts.
import fontUrl from './ma-shan-zheng-0a5055c7.ttf' with { type: 'url' };
import glyphData from './glyphData.json' with { type: 'json' };

const bundle = {
  version: 0,
  family: 'Ma Shan Zheng Tegaki 0a5055c7',
  lineCap: 'round',
  fontUrl,
  fontFaceCSS: `@font-face { font-family: 'Ma Shan Zheng Tegaki 0a5055c7'; src: url(${fontUrl}); }`,
  unitsPerEm: 1000,
  ascender: 880,
  descender: -120,
  glyphData,
} as const;

export default bundle;
