'use client';
import {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useMemo,
  useRef,
  useState,
  useSyncExternalStore,
} from 'react';
import { Moon, Sun, RotateCcw, SkipBack, Volume2, VolumeX } from 'lucide-react';
import {
  Button,
  NativeSelect,
  NativeSelectOption,
  Slider,
} from './controls.tsx';
import { formatTime } from './timing.ts';
import {
  BoardMarks,
  BoardRenderer,
  HandwrittenLine,
  HandwritingProvider,
  clamp01,
  latinHandwritingBundle,
} from './board/index.tsx';
import { defaultVisualRegistry } from './grammars/index.ts';
import {
  ClassroomClock,
  initialPlayback,
  type PlaybackSnapshot,
} from './clock.ts';
import {
  classroomAt,
  prepareLesson,
  type PreparedLesson,
  type VisualRegistry,
} from './runtime.ts';
import type { LessonSpec } from '@learn-anything/lesson-schema';
import {
  CHINESE_FONTS,
  LATIN_FONTS,
  DEFAULT_FONTS,
  parseFontSelection,
  loadChineseFont,
  loadLatinFont,
  type FontSelection,
  type ChineseFontLoader,
} from './font-presets.ts';
import {
  savedFontSnapshot,
  initialFontSnapshot,
  subscribeFonts,
  saveFonts,
} from './font-preferences.ts';
import type { TegakiBundle } from 'tegaki/core';
export {
  CHINESE_FONTS,
  LATIN_FONTS,
  DEFAULT_FONTS,
  parseFontSelection,
  loadChineseFont,
  loadLatinFont,
} from './font-presets.ts';
export type {
  FontSelection,
  ChineseFontId,
  LatinFontId,
  ChineseFontLoader,
} from './font-presets.ts';
import { TeachingBoard } from './teaching-board.tsx';
import {
  savedTheme,
  initialTheme,
  subscribeTheme,
  saveTheme,
} from './theme.ts';
export { ClassroomClock, classroomAt, prepareLesson };
export type { ClassroomTheme } from './board/index.tsx';
export { createVisualRegistry, registerGrammar } from './runtime.ts';
export type {
  VisualGrammar,
  VisualProps,
  VisualRegistry,
  ClassroomFrame,
} from './runtime.ts';
export type { LessonSpec, TimelineEvent } from '@learn-anything/lesson-schema';
export type { PlaybackSnapshot } from './clock.ts';
export type ClassroomHandle = {
  play(): Promise<void>;
  pause(): void;
  seek(seconds: number): void;
  restart(): void;
  setSpeed(speed: number): void;
  setMuted(muted: boolean): void;
  getSnapshot(): PlaybackSnapshot | null;
};
export type ClassroomPlayerProps = {
  lesson: LessonSpec;
  registry?: VisualRegistry;
  onPlaybackChange?: (snapshot: PlaybackSnapshot) => void;
  /** Local hosts can persist preferences across changing ports. */
  initialFonts?: FontSelection;
  onFontSelectionChange?: (fonts: FontSelection) => void | Promise<void>;
  /** Optional course-specific paths generated by the host, never by React. */
  loadChineseFont?: ChineseFontLoader;
};
export function ClassroomSurface({
  prepared,
  time,
  playing = false,
  video = false,
  style,
}: {
  prepared: PreparedLesson;
  time: number;
  playing?: boolean;
  /** Export presentation: show the current teaching segment without scrolling. */
  video?: boolean;
  /** Teaching font variables stay on the board so controls keep their fonts. */
  style?: React.CSSProperties;
}) {
  const frame = classroomAt(prepared, time),
    { lesson } = prepared,
    p = lesson.presentation;
  return (
    <section
      className="paper-board"
      aria-label={`${lesson.title}全屏手写板`}
      style={style}
    >
      <header className="paper-heading">
        <h1>
          <HandwrittenLine
            item={{
              at: p.titleAt,
              id: 'lesson-title',
              text: lesson.title,
              tone: 'accent',
            }}
            time={time}
            underline
          />
        </h1>
        <div className="paper-meta">
          <HandwrittenLine
            item={{
              at: p.metaAt,
              id: 'lesson-meta',
              text: lesson.eyebrow,
              tone: 'plain',
            }}
            time={time}
          />
        </div>
      </header>
      {lesson.teaching ? (
        <TeachingBoard
          prepared={prepared}
          time={time}
          playing={playing}
          video={video}
        />
      ) : (
        <div className="board-flow">
          <section className="board-diagram" aria-label={p.diagramTitle}>
            <div className="stage-topline">
              <HandwrittenLine
                item={{
                  at: p.diagramTitleAt,
                  id: 'diagram-title',
                  text: p.diagramTitle,
                  tone: 'label',
                }}
                time={time}
              />
            </div>
            {frame.visuals.map((visual) => (
              <div
                key={visual.id}
                data-visual-id={visual.id}
                data-grammar={visual.grammar.id}
              >
                <visual.grammar.Renderer
                  config={visual.config}
                  state={visual.state}
                  time={time}
                />
              </div>
            ))}
            <BoardMarks marks={frame.marks} region="diagram" time={time} />
          </section>
          <section className="board-writing" aria-label="逐步手写推导">
            <div className="board-header">
              <HandwrittenLine
                item={{
                  at: p.notesTitleAt,
                  id: 'notes-title',
                  text: p.notesTitle,
                  tone: 'accent',
                }}
                time={time}
                underline
              />
            </div>
            <div
              className="chalk-rule"
              style={
                {
                  '--ink': clamp01((time - p.ruleAt) / 0.75),
                } as React.CSSProperties
              }
            />
            <BoardRenderer
              items={frame.board}
              marks={frame.marks.filter((mark) => mark.region === 'notes')}
              time={time}
            />
          </section>
        </div>
      )}
    </section>
  );
}
const PreparedPlayer = forwardRef<
  ClassroomHandle,
  {
    prepared: PreparedLesson;
    onPlaybackChange?: ClassroomPlayerProps['onPlaybackChange'];
    initialFonts?: FontSelection;
    onFontSelectionChange?: ClassroomPlayerProps['onFontSelectionChange'];
    loadChineseFont?: ChineseFontLoader;
  }
>(function PreparedPlayer(
  {
    prepared,
    onPlaybackChange,
    initialFonts,
    onFontSelectionChange,
    loadChineseFont: chineseLoader,
  },
  ref,
) {
  const { lesson } = prepared;
  const browserFonts = useSyncExternalStore(
    subscribeFonts,
    savedFontSnapshot,
    initialFontSnapshot,
  );
  const [requestedFonts, setFonts] = useState<FontSelection | undefined>();
  const fonts = useMemo(
    () =>
      requestedFonts ??
      initialFonts ??
      parseFontSelection(JSON.parse(browserFonts)),
    [requestedFonts, initialFonts, browserFonts],
  );
  const [appliedFonts, setAppliedFonts] = useState<{
    selection: FontSelection;
    chinese?: TegakiBundle;
    latin?: TegakiBundle;
  }>({ selection: { ...DEFAULT_FONTS } });
  const [fontsReady, setFontsReady] = useState(false);
  const appliedSelection = useRef(appliedFonts.selection);
  const [fontError, setFontError] = useState('');
  const fontCallback = useRef(onFontSelectionChange);
  const interacted = useRef(false);
  useEffect(() => {
    fontCallback.current = onFontSelectionChange;
  }, [onFontSelectionChange]);
  useEffect(() => {
    let active = true;
    void Promise.all([
      fonts.chinese === 'ma-shan-zheng'
        ? Promise.resolve(undefined)
        : loadChineseFont(fonts.chinese, chineseLoader),
      loadLatinFont(fonts.latin),
    ])
      .then(async ([chinese, latin]) => {
        if (!active) return;
        setAppliedFonts({ selection: fonts, chinese, latin });
        appliedSelection.current = fonts;
        setFontsReady(true);
        if (interacted.current) {
          saveFonts(fonts);
          try {
            await fontCallback.current?.(fonts);
          } catch {
            if (active)
              setFontError('字体已切换，但未能保存偏好；请重新选择后重试。');
          }
        }
      })
      .catch(() => {
        if (!active) return;
        setFontsReady(true);
        setFontError('字体载入失败，仍使用切换前的字体；请重新选择后重试。');
        setFonts(appliedSelection.current);
      });
    return () => {
      active = false;
    };
    // Applied fonts remain visible until both matching resources are ready.
    // Updating them never re-mounts the audio clock or changes lesson time.
  }, [fonts, chineseLoader]);
  const fontLoading =
    !fontError &&
    (!fontsReady ||
      fonts.chinese !== appliedFonts.selection.chinese ||
      fonts.latin !== appliedFonts.selection.latin);
  const selectFonts = (next: FontSelection) => {
    setFontError('');
    interacted.current = true;
    setFonts(parseFontSelection(next));
  };
  const theme = useSyncExternalStore(subscribeTheme, savedTheme, initialTheme);
  const toggleTheme = () => saveTheme(theme === 'light' ? 'dark' : 'light');
  const audioRef = useRef<HTMLAudioElement>(null),
    clockRef = useRef<ClassroomClock | null>(null),
    callbackRef = useRef(onPlaybackChange);
  useEffect(() => {
    callbackRef.current = onPlaybackChange;
  }, [onPlaybackChange]);
  const [playback, setPlayback] = useState(() =>
    initialPlayback(lesson.duration),
  );
  const frame = useMemo(
    () => classroomAt(prepared, playback.time),
    [prepared, playback.time],
  );
  useEffect(() => {
    if (!audioRef.current) return;
    const clock = new ClassroomClock(audioRef.current, lesson.duration, {
      request: (callback) => requestAnimationFrame(callback),
      cancel: (id) => cancelAnimationFrame(id),
    });
    clockRef.current = clock;
    const unsubscribe = clock.subscribe((snapshot) => {
      setPlayback(snapshot);
      callbackRef.current?.(snapshot);
    });
    return () => {
      unsubscribe();
      clock.destroy();
      clockRef.current = null;
    };
  }, [lesson]);
  useImperativeHandle(
    ref,
    () => ({
      play: async () => {
        await clockRef.current?.play();
      },
      pause: () => clockRef.current?.pause(),
      seek: (seconds) => clockRef.current?.seek(seconds),
      restart: () => clockRef.current?.restart(),
      setSpeed: (speed) => clockRef.current?.setSpeed(speed),
      setMuted: (muted) => clockRef.current?.setMuted(muted),
      getSnapshot: () => clockRef.current?.getSnapshot() ?? null,
    }),
    [],
  );
  return (
    <HandwritingProvider
      bundle={lesson.handwriting}
      theme={theme}
      chineseFont={appliedFonts.chinese}
      latinFont={appliedFonts.latin}
    >
      <main
        className="classroom-shell"
        data-theme={theme}
        data-chinese-font={appliedFonts.selection.chinese}
        data-latin-font={appliedFonts.selection.latin}
        data-font-loading={fontLoading}
        data-lesson-id={lesson.id}
        data-classroom-time={playback.time}
        data-classroom-ready={playback.ready}
        data-board-mode={lesson.teaching ? 'full-narration' : undefined}
        style={
          {
            '--font-hand-latin': `"${latinHandwritingBundle.family}"`,
          } as React.CSSProperties
        }
      >
        <audio ref={audioRef} src={lesson.audio} preload="auto">
          <track
            kind="captions"
            src={lesson.captions}
            srcLang="zh-CN"
            label="中文"
          />
        </audio>
        <ClassroomSurface
          prepared={prepared}
          time={playback.time}
          playing={playback.playing}
          style={
            {
              ...(appliedFonts.chinese
                ? { '--font-hand': `"${appliedFonts.chinese.family}"` }
                : {}),
              '--font-hand-latin': `"${(appliedFonts.latin ?? latinHandwritingBundle).family}"`,
            } as React.CSSProperties
          }
        />
        {playback.error && (
          <p role="alert" className="classroom-error">
            {playback.error}
          </p>
        )}
        <section className="player-dock" aria-label="课程播放控制">
          <div className="timeline-control">
            <div className="timeline-meta">
              <span>{formatTime(playback.time)}</span>
              <span className="narration-state">
                {lesson.chapters.find(
                  (chapter) => chapter.id === frame.chapterId,
                )?.label ??
                  `${frame.narrationIndex + 1} / ${lesson.narration.length}`}
              </span>
              <span>{formatTime(lesson.duration)}</span>
            </div>
            <Slider
              aria-label="课程进度"
              min={0}
              max={lesson.duration}
              step={0.05}
              value={[playback.time]}
              onValueChange={(value) =>
                clockRef.current?.seek(
                  Array.isArray(value) ? (value[0] ?? 0) : value,
                )
              }
            />
            <div className="chapter-ticks" aria-hidden="true">
              {lesson.chapters.slice(1).map((chapter) => (
                <span
                  key={chapter.id}
                  style={{ left: `${(chapter.at / lesson.duration) * 100}%` }}
                />
              ))}
            </div>
          </div>
          <div className="controls-center">
            <Button
              type="button"
              variant="ghost"
              size="icon-lg"
              onClick={() => clockRef.current?.restart()}
              aria-label="重新开始"
              title="重新开始"
            >
              <RotateCcw aria-hidden="true" />
            </Button>
            <Button
              type="button"
              variant="ghost"
              size="icon-lg"
              onClick={() => clockRef.current?.seek(playback.time - 10)}
              aria-label="后退十秒"
              title="后退十秒"
            >
              <SkipBack aria-hidden="true" />
              <span className="skip-number">10</span>
            </Button>
            <button
              type="button"
              disabled={Boolean(playback.error)}
              className={
                playback.playing ? 'play-toggle is-playing' : 'play-toggle'
              }
              onClick={() =>
                playback.playing
                  ? clockRef.current?.pause()
                  : void clockRef.current?.play()
              }
              aria-label={playback.playing ? '暂停' : '播放'}
            >
              <span className="play-icon" aria-hidden="true" />
            </button>
            <Button
              type="button"
              variant="ghost"
              size="icon-lg"
              onClick={() => clockRef.current?.setMuted(!playback.muted)}
              aria-label={playback.muted ? '打开声音' : '关闭声音'}
              title={playback.muted ? '打开声音' : '关闭声音'}
            >
              {playback.muted ? (
                <VolumeX aria-hidden="true" />
              ) : (
                <Volume2 aria-hidden="true" />
              )}
            </Button>
            <NativeSelect
              aria-label="播放速度"
              value={playback.speed}
              onChange={(event) =>
                clockRef.current?.setSpeed(Number(event.target.value))
              }
            >
              {[0.75, 1, 1.25, 1.5].map((value) => (
                <NativeSelectOption key={value} value={value}>
                  {value}×
                </NativeSelectOption>
              ))}
            </NativeSelect>
            <Button
              type="button"
              variant="ghost"
              size="icon-lg"
              onClick={toggleTheme}
              aria-label={theme === 'light' ? '切换到深色' : '切换到浅色'}
              aria-pressed={theme === 'dark'}
              title={theme === 'light' ? '切换到深色' : '切换到浅色'}
            >
              {theme === 'light' ? (
                <Moon aria-hidden="true" />
              ) : (
                <Sun aria-hidden="true" />
              )}
            </Button>
          </div>
          <details className="font-settings">
            <summary>字体</summary>
            <div className="font-options">
              <label>
                中文
                <NativeSelect
                  aria-label="中文字体"
                  value={fonts.chinese}
                  onChange={(event) =>
                    selectFonts({
                      ...fonts,
                      chinese: event.target.value as FontSelection['chinese'],
                    })
                  }
                >
                  {CHINESE_FONTS.map((font) => (
                    <NativeSelectOption key={font.id} value={font.id}>
                      {font.label}
                    </NativeSelectOption>
                  ))}
                </NativeSelect>
              </label>
              <label>
                英文／数字
                <NativeSelect
                  aria-label="英文和数字字体"
                  value={fonts.latin}
                  onChange={(event) =>
                    selectFonts({
                      ...fonts,
                      latin: event.target.value as FontSelection['latin'],
                    })
                  }
                >
                  {LATIN_FONTS.map((font) => (
                    <NativeSelectOption key={font.id} value={font.id}>
                      {font.label}
                    </NativeSelectOption>
                  ))}
                </NativeSelect>
              </label>
            </div>
            {fontLoading && (
              <output className="font-status">正在准备字体…</output>
            )}
            {fontError && (
              <p className="font-status" role="alert">
                {fontError}
              </p>
            )}
          </details>
        </section>
      </main>
    </HandwritingProvider>
  );
});
export const ClassroomPlayer = forwardRef<
  ClassroomHandle,
  ClassroomPlayerProps
>(function ClassroomPlayer(
  {
    lesson,
    registry = defaultVisualRegistry,
    onPlaybackChange,
    initialFonts,
    onFontSelectionChange,
    loadChineseFont,
  },
  ref,
) {
  const result = useMemo(() => {
    try {
      return prepareLesson(lesson, registry);
    } catch {
      return null;
    }
  }, [lesson, registry]);
  if (!result)
    return (
      <p role="alert" className="classroom-error">
        课程数据或动画语法无效，无法播放。
      </p>
    );
  return (
    <PreparedPlayer
      key={JSON.stringify(result.lesson)}
      ref={ref}
      prepared={result}
      onPlaybackChange={onPlaybackChange}
      initialFonts={initialFonts}
      onFontSelectionChange={onFontSelectionChange}
      loadChineseFont={loadChineseFont}
    />
  );
});
